-- Snowflake setup for IR RAG demo
-- Run this in Snowsight/Worksheet with a role that can create DB/objects

-- 1) Create database and schemas
CREATE DATABASE IF NOT EXISTS IRINFO_RAG;
USE DATABASE IRINFO_RAG;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS CURATED;
USE SCHEMA CURATED;

-- 2) Create internal stage used by the app (with directory listing enabled)
CREATE STAGE IF NOT EXISTS IRINFO_RAG.RAW.IR_STAGE
  DIRECTORY = (ENABLE = TRUE);

-- 3) Optional: refresh directory listing after you upload files
-- ALTER STAGE IRINFO_RAG.RAW.IR_STAGE REFRESH;

-- 4) Create tables used by the app (idempotent)
CREATE TABLE IF NOT EXISTS CURATED.PAGES_AI_PARSE (
  DOC_ID        STRING,
  PAGE_NUM      NUMBER,
  PAGE_CONTENT  STRING,
  PARSE_MODE    STRING,
  LOAD_TS       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CURATED.PAGE_EVAL_LOG (
  DOC_ID     STRING,
  PAGE_NUM   NUMBER,
  MODEL      STRING,
  IMAGE_PATH STRING,
  RESULT     STRING,
  LOAD_TS    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CURATED.PAGES_AI_PARSE_CURATED (
  DOC_ID        STRING,
  PAGE_NUM      NUMBER,
  PARSE_MODE    STRING,
  PAGE_CONTENT  STRING,
  LLM_OUTPUT    STRING,
  CURATED_TEXT  STRING,
  LOAD_TS       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 5) (Optional) Grants for a shared role
-- Replace ROLE_NAME with the role that will run the Streamlit app
-- GRANT USAGE ON DATABASE IRINFO_RAG TO ROLE ROLE_NAME;
-- GRANT USAGE ON SCHEMA IRINFO_RAG.RAW TO ROLE ROLE_NAME;
-- GRANT USAGE ON SCHEMA IRINFO_RAG.CURATED TO ROLE ROLE_NAME;
-- GRANT READ, USAGE ON STAGE IRINFO_RAG.RAW.IR_STAGE TO ROLE ROLE_NAME;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA IRINFO_RAG.CURATED TO ROLE ROLE_NAME;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA IRINFO_RAG.CURATED TO ROLE ROLE_NAME;

